apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: valkey://{.spec.clusterIP}:{.spec.ports[?(.name=="valkey")].port}
  labels:
    template: valkey-cluster-template
  name: {{ .Values.database_service_name }}-master
spec:
  ports:
  - name: valkey
    port: 6379
    protocol: TCP
    targetPort: 6379
  {{- if .Values.tls.enabled }}
  - name: valkey-tls
    port: 6380
    protocol: TCP
    targetPort: 6380
  {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.database_service_name }}-0
  type: ClusterIP
