apiVersion: v1
kind: Service
metadata:
  labels:
    template: valkey-cluster-template
  name: {{ .Values.database_service_name }}-read
spec:
  ports:
  - name: valkey
    port: 6379
    protocol: TCP
    targetPort: 6379
  {{- if .Values.tls.enabled }}
  - name: valkey-tls
    port: 6380
    protocol: TCP
    targetPort: 6380
  {{- end }}
  selector:
    name: {{ .Values.database_service_name }}
  type: ClusterIP
