apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    template: valkey-cluster-template
  name: {{ .Values.database_service_name }}
spec:
  serviceName: {{ .Values.database_service_name }}-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.database_service_name }}
  template:
    metadata:
      labels:
        name: {{ .Values.database_service_name }}
    spec:
      containers:
      - name: valkey
        env:
        - name: VALKEY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.database_service_name }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/valkey:{{ .Values.valkey_version }}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          POD_FQDN="${POD_NAME}.{{ .Values.database_service_name }}-headless.{{ .Release.Namespace }}.svc.cluster.local"
          CLUSTER_ARGS="--cluster-enabled yes --cluster-config-file /var/lib/valkey/data/nodes.conf --cluster-node-timeout 5000"
          CLUSTER_ANNOUNCE="--cluster-announce-hostname ${POD_FQDN}"
          {{- if .Values.tls.enabled }}
          CLUSTER_ANNOUNCE="${CLUSTER_ANNOUNCE} --cluster-announce-tls-port 6380 --cluster-announce-bus-port 16380"
          TLS_ARGS="--port 0 --tls-port 6380 --tls-cert-file /tls/tls.crt --tls-key-file /tls/tls.key --tls-ca-cert-file /service-ca/service-ca.crt --tls-auth-clients no"
          {{- else }}
          CLUSTER_ANNOUNCE="${CLUSTER_ANNOUNCE} --cluster-announce-port 6379 --cluster-announce-bus-port 16379"
          TLS_ARGS=""
          {{- end }}
          exec valkey-server --dir /var/lib/valkey/data \
            --requirepass "$VALKEY_PASSWORD" \
            --masterauth "$VALKEY_PASSWORD" \
            $CLUSTER_ARGS \
            $CLUSTER_ANNOUNCE \
            $TLS_ARGS
        ports:
        - containerPort: 6379
          protocol: TCP
        {{- if .Values.tls.enabled }}
        - containerPort: 6380
          protocol: TCP
        {{- end }}
        - containerPort: 16379
          name: cluster-bus
          protocol: TCP
        {{- if .Values.tls.enabled }}
        - containerPort: 16380
          name: cluster-bus-tls
          protocol: TCP
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 30
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            {{- if .Values.tls.enabled }}
            - test "$(valkey-cli -h 127.0.0.1 -a $VALKEY_PASSWORD --tls --cert /tls/tls.crt --key /tls/tls.key --cacert /service-ca/service-ca.crt -p 6380 ping)" == "PONG"
            {{- else }}
            - test "$(valkey-cli -h 127.0.0.1 -a $VALKEY_PASSWORD ping)" == "PONG"
            {{- end }}
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            {{- if .Values.tls.enabled }}
            - test "$(valkey-cli -h 127.0.0.1 -a $VALKEY_PASSWORD --tls --cert /tls/tls.crt --key /tls/tls.key --cacert /service-ca/service-ca.crt -p 6380 ping)" == "PONG"
            {{- else }}
            - test "$(valkey-cli -h 127.0.0.1 -a $VALKEY_PASSWORD ping)" == "PONG"
            {{- end }}
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: {{ .Values.memory_limit }}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/valkey/data
          name: {{ .Values.database_service_name }}-data
        {{- if .Values.tls.enabled }}
        - mountPath: /tls
          name: tls-certs
          readOnly: true
        - mountPath: /service-ca
          name: service-ca
          readOnly: true
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- if .Values.tls.enabled }}
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ .Values.tls.secretName }}
      - name: service-ca
        configMap:
          name: {{ .Values.database_service_name }}-service-ca
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.database_service_name }}-data
      labels:
        template: valkey-cluster-template
      {{- if .Values.pvc.netapp_nfs }}
      annotations:
        trident.netapp.io/reclaimPolicy: Delete
      {{- end }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.pvc.volume_capacity }}
      {{- if .Values.pvc.netapp_nfs }}
      storageClassName: netapp-nfs
      volumeMode: Filesystem
      {{- end }}
